/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_2;

import java.util.List;
import javafx.util.Pair;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Heiner
 */
public class PageTable extends javax.swing.JDialog {

    DefaultTableModel modeloTablaPageTable;
    
    /**
     * Creates new form Configuracion
     * @param parent
     * @param modal
     * @param proceso
     */
    public PageTable(java.awt.Frame parent, boolean modal, Proceso proceso) {
        super(parent, modal);
        initComponents();
        this.lbNombreProceso.setText(proceso.obtenerNombre());
        this.modeloTablaPageTable = (DefaultTableModel) jtPageTable.getModel();
        cargarPageTable(proceso.obtenerFrames());
        this.setLocationRelativeTo(parent);
    }
    
    /**
     * Carga a la tabla configuracion los pesos de la instrucciones establecidos...
     * ...en la clase TiempoInstrucciones.
     */
    private void cargarPageTable(List<Pair<Integer, Integer>> frames){
        int cantidadFrames = frames.size();
        Pair<Integer, Integer> frame;
        for(int i = 0; i < cantidadFrames; i++){
            frame = frames.get(i);
            if(frame.getKey() < CPU.LARGOMEMORIA){
                modeloTablaPageTable.addRow(new Object[]{ i, frame.getKey() +
                        "(M:" + frame.getKey() + ")" });
            }else{
                modeloTablaPageTable.addRow(new Object[]{ i, frame.getKey() +
                        "(D:" + (frame.getKey() - CPU.LARGOMEMORIA) + ")" });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtPageTable = new javax.swing.JTable();
        btAceptar = new javax.swing.JButton();
        lbNombreProceso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Page Table");

        jtPageTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtPageTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Page", "Frame"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtPageTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtPageTable);

        btAceptar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btAceptar.setText("Aceptar");
        btAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAceptarActionPerformed(evt);
            }
        });

        lbNombreProceso.setText("NOMBRE DEL PROCESO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btAceptar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbNombreProceso)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbNombreProceso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btAceptar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAceptarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btAceptarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAceptar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtPageTable;
    private javax.swing.JLabel lbNombreProceso;
    // End of variables declaration//GEN-END:variables
}
