/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_2;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Heiner
 */
public class PanelSegmentacion extends javax.swing.JPanel {
    
    private DefaultTableModel modeloTablaSegmentos;
    
    /**
     * Creates new form PanelPaginacion
     * @param memoria
     */
    public PanelSegmentacion(int memoria) {
        initComponents();
        this.modeloTablaSegmentos = (DefaultTableModel) jtSegmentos.getModel();
        agregarSegmento(memoria/2);
    }
    
    private void agregarSegmento(int tamanio){
        this.modeloTablaSegmentos.addRow(new Object[]{ "Segmento "+modeloTablaSegmentos.getRowCount(), tamanio });
    }
    
    public int[] obtenerSegmentos(){
        int cantidadFilas = modeloTablaSegmentos.getRowCount();
        int[] tamanioSegmentos = new int[cantidadFilas];
        for(int i = 0; i < cantidadFilas; i++){
            tamanioSegmentos[i] = (int)modeloTablaSegmentos.getValueAt(i, 1);
        }
        return tamanioSegmentos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtSegmentos = new javax.swing.JTable();
        btAgregarSegmento = new javax.swing.JButton();
        btBorrarSegmento = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Configuración del algoritmo Memoria");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Establezca los segmentos");

        jtSegmentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Segmento", "Tamaño"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtSegmentos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtSegmentos);
        if (jtSegmentos.getColumnModel().getColumnCount() > 0) {
            jtSegmentos.getColumnModel().getColumn(0).setResizable(false);
            jtSegmentos.getColumnModel().getColumn(1).setResizable(false);
        }

        btAgregarSegmento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btAgregarSegmento.setText("Agregar");
        btAgregarSegmento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgregarSegmentoActionPerformed(evt);
            }
        });

        btBorrarSegmento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btBorrarSegmento.setText("Borrar");
        btBorrarSegmento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBorrarSegmentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(1, 1, 1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btBorrarSegmento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btAgregarSegmento)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAgregarSegmento)
                    .addComponent(btBorrarSegmento))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btAgregarSegmentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgregarSegmentoActionPerformed
        agregarSegmento(1);
    }//GEN-LAST:event_btAgregarSegmentoActionPerformed

    private void btBorrarSegmentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBorrarSegmentoActionPerformed
        int fila = jtSegmentos.getSelectedRow();
        if(fila != -1){
            if(jtSegmentos.getRowCount() > 1){
                modeloTablaSegmentos.removeRow(fila);
                int cantidadFilas = jtSegmentos.getRowCount();
                for(int i = 0; i < cantidadFilas; i++){
                    modeloTablaSegmentos.setValueAt("Segmento "+i, i, 0);
                }
            }
        }
    }//GEN-LAST:event_btBorrarSegmentoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAgregarSegmento;
    private javax.swing.JButton btBorrarSegmento;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtSegmentos;
    // End of variables declaration//GEN-END:variables
}
